// Stamp the current git build identity into src/build-info.ts.
//
// Cloudflare Workers have no git at runtime, so we capture the commit + build
// time at build/deploy time and bundle it. This is the UNSIGNED build identity
// surfaced at /version, in /health, and the UI footer. The signed build-receipt
// layer (a provenance signature over these fields) will EXTEND this object, not
// replace it - keep that in mind before restructuring.
//
// Runs automatically via the pre* npm hooks and the wrangler [build] command.
// Safe to run standalone: `node scripts/stamp-build.mjs`.

import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const git = (cmd) => {
  try {
    return execSync(`git ${cmd}`, { cwd: root, stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
  } catch {
    return "";
  }
};

const commit = git("rev-parse HEAD") || "unknown";
// "dirty" = uncommitted changes, EXCLUDING this generated file (it rewrites
// itself every run, so counting it would make dirty always true).
const dirty =
  git("status --porcelain")
    .split("\n")
    .filter((l) => l && !l.includes("src/build-info.ts")).length > 0;
const branch = git("rev-parse --abbrev-ref HEAD") || "unknown";
const builtAt = new Date().toISOString();

const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const provenanceVersion =
  String(pkg.dependencies?.["@drm3labs-oss/provenance"] || "")
    .replace(/^[^0-9]*/, "") || "unknown";

const info = {
  commit,
  shortCommit: commit.slice(0, 7),
  branch,
  dirty,
  builtAt,
  provenanceVersion,
};

writeFileSync(
  join(root, "src", "build-info.ts"),
  `// GENERATED by scripts/stamp-build.mjs at build/deploy time. Do not edit by hand.
// The signed build-receipt layer will extend BUILD_INFO with a provenance
// signature over these fields; it will not replace them.
export const BUILD_INFO = ${JSON.stringify(info, null, 2)} as const;
`,
);

console.log(
  `stamp-build: ${info.shortCommit}${dirty ? "-dirty" : ""} @ ${builtAt} (provenance ${provenanceVersion})`,
);
